sudo: false
language: php
php:
  - 5.6
  - 7.1
  - 7.2
before_script:
  - composer self-update
  - composer install
script:
  - phpunit --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
