<?php

namespace Victormln\LaravelTactician\Tests\Commands;

use Illuminate\Support\Facades\Artisan;
use Victormln\LaravelTactician\Tests\TestCase;

/**
 * Class TestGenerators
 * @package Victormln\LaravelTactician\Tests\Generators
 */
class TestGenerators extends TestCase
{

    /**
     * Setup the test environment.
     *
     * @return void
     */
    public function setUp(): void
    {
        $this->clearTempFiles();
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * Clean up the testing environment before the next test.
     *
     * @return void
     */
    public function tearDown(): void
    {
        $this->clearTempFiles();
        parent::tearDown();
    }

    /**
     * Clear the files that tests generated
     */
    protected function clearTempFiles(): void
    {
        if (file_exists($this->getExpectedCommandFile())) {
            unlink($this->getExpectedCommandFile());
        }

        if (file_exists($this->getExpectedHandlerFile())) {
            unlink($this->getExpectedHandlerFile());
        }
    }

    /**
     * Generate Command and Command Handler using Artisan
     */
    protected function makeCommandAndCommandHandler(): void
    {
        Artisan::call('make:tactician', ['name' => 'Foo']);
    }

    /**
     * Generate Command using Artisan
     */
    protected function makeCommand(): void
    {
        Artisan::call('make:tactician:command', ['name' => 'Foo']);
    }

    /**
     * Generate Handler using Artisan
     */
    protected function makeHandler(): void
    {
        Artisan::call('make:tactician:handler', ['name' => 'Foo']);
    }


    protected function getExpectedCommandFile(): string
    {
        return __DIR__ . '/../../vendor/orchestra/testbench-core/laravel/app/CommandBus/Commands/FooCommand.php';
    }

    protected function getExpectedHandlerFile(): string
    {
        return __DIR__ . '/../../vendor/orchestra/testbench-core/laravel/app/CommandBus/Handlers/FooHandler.php';
    }

    /**
     * Test Command file is created
     */
    public function test_it_creates_command(): void
    {
        $this->makeCommand();

        $this->assertTrue(file_exists($this->getExpectedCommandFile()));
    }

    public function test_it_creates_command_and_command_handler(): void
    {
        $this->makeCommandAndCommandHandler();

        // Test command
        $this->assertTrue(file_exists($this->getExpectedCommandFile()));
        $this->assertTrue(strpos(file_get_contents($this->getExpectedCommandFile()), 'Class FooCommand') !== false);
        $this->assertTrue(strpos(file_get_contents($this->getExpectedCommandFile()), 'class FooCommand') !== false);
        $this->assertTrue(strpos(file_get_contents($this->getExpectedCommandFile()), 'FooCommand constructor') !== false);
        $this->assertTrue(strpos(file_get_contents($this->getExpectedCommandFile()), 'namespace App\CommandBus\Commands;') !== false);

        // Test command handler
        $this->assertTrue(file_exists($this->getExpectedHandlerFile()));
        $this->assertTrue(strpos(file_get_contents($this->getExpectedHandlerFile()), 'Class FooHandler') !== false);
        $this->assertTrue(strpos(file_get_contents($this->getExpectedHandlerFile()), 'class FooHandler') !== false);
        $this->assertTrue(strpos(file_get_contents($this->getExpectedHandlerFile()), 'FooHandler constructor') !== false);
        $this->assertTrue(strpos(file_get_contents($this->getExpectedHandlerFile()), 'namespace App\CommandBus\Handlers;') !== false);
    }

    /**
     * Test DummyClass is replaced correctly in Command
     */
    public function test_it_names_command(): void
    {
        $this->makeCommand();

        $this->assertTrue(strpos(file_get_contents($this->getExpectedCommandFile()), 'Class FooCommand') !== false);
        $this->assertTrue(strpos(file_get_contents($this->getExpectedCommandFile()), 'class FooCommand') !== false);
        $this->assertTrue(strpos(file_get_contents($this->getExpectedCommandFile()), 'FooCommand constructor') !== false);
    }

    /**
     * Test DummyNamespace is replaced correctly in Command
     */
    public function test_it_namespaces_command(): void
    {
        $this->makeCommand();

        $this->assertTrue(strpos(file_get_contents($this->getExpectedCommandFile()), 'namespace App\CommandBus\Commands;') !== false);
    }

    /**
     * Test Handler file is created
     */
    public function test_it_creates_handler(): void
    {
        $this->makeHandler();

        $this->assertTrue(file_exists($this->getExpectedHandlerFile()));
    }

    /**
     * Test DummyClass is replaced correctly in Handler
     */
    public function test_it_names_handler(): void
    {
        $this->makeHandler();

        $this->assertTrue(strpos(file_get_contents($this->getExpectedHandlerFile()), 'Class FooHandler') !== false);
        $this->assertTrue(strpos(file_get_contents($this->getExpectedHandlerFile()), 'class FooHandler') !== false);
        $this->assertTrue(strpos(file_get_contents($this->getExpectedHandlerFile()), 'FooHandler constructor') !== false);
    }

    /**
     * Test DummyNamespace is replaced correctly in Handler
     */
    public function test_it_namespaces_handler(): void
    {
        $this->makeHandler();

        $this->assertTrue(strpos(file_get_contents($this->getExpectedHandlerFile()), 'namespace App\CommandBus\Handlers;') !== false);
    }

    /**
     * Test instance of Command is injected to Handler
     */
    public function test_it_adds_handler_to_command(): void
    {
        $this->makeHandler();

        $this->assertTrue(strpos(file_get_contents($this->getExpectedHandlerFile()), '* @param FooCommand $command') !== false);
        $this->assertTrue(strpos(file_get_contents($this->getExpectedHandlerFile()), 'public function handle(FooCommand $command)') !== false);
    }
}
